# Generated by Django 3.1.3 on 2020-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201114_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='static/aftermath.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
