# Generated by Django 3.1.2 on 2020-10-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
