# Generated by Django 3.1.2 on 2020-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0002_auto_20201031_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
