# Generated by Django 3.1.3 on 2020-11-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0005_auto_20201110_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
