# Generated by Django 3.1.3 on 2020-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0006_auto_20201114_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/hmklz8dtf/image/upload/v1/media/users/2020/11/14/3abc6275419f468bf41a10b64a90f31b--st-etienne-cathedrals_jqbogy', upload_to='images/%Y/%m/%d/'),
        ),
    ]
