# Generated by Django 3.1.3 on 2020-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
