# Generated by Django 3.1.3 on 2020-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='content',
            field=models.TextField(default='Start learning today'),
            preserve_default=False,
        ),
    ]
