# Generated by Django 3.1.3 on 2020-12-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201211_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated']},
        ),
    ]
