# Generated by Django 3.1.3 on 2020-12-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20201212_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
