# Generated by Django 3.1.3 on 2020-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(default='place.jpg', upload_to='images'),
        ),
    ]
