# Generated by Django 3.1.3 on 2020-12-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20201212_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(upload_to='images'),
        ),
    ]
