# Generated by Django 3.1.3 on 2020-12-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20201212_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated']},
        ),
    ]
