# Generated by Django 3.1.3 on 2020-12-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20201212_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
