# Generated by Django 3.1.3 on 2020-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20201212_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(default='https://res.cloudinary.com/hmklz8dtf/image/upload/v1/media/images/python_xpcvgr', upload_to='images'),
        ),
    ]
