# Generated by Django 3.1.3 on 2020-12-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20201214_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.Subject'),
        ),
    ]
